;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/Lead/Content/Localization/Lead
DestinationPath=Mods/GameFeatures/Lead/Content/Localization/Lead
ManifestName=Lead.manifest
ArchiveName=Lead.archive
ResourceName=Lead.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
bValidateRichTextTags=false
NativeCulture=en
CulturesToGenerate=cs
CulturesToGenerate=de
CulturesToGenerate=en
CulturesToGenerate=ja
CulturesToGenerate=ko
CulturesToGenerate=pl
CulturesToGenerate=ru
CulturesToGenerate=zh

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

