;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Saved/Tolgee/Temp/Lead
DestinationPath=Mods/GameFeatures/Lead/Content/Localization/Lead
NativeCulture=en
CulturesToGenerate=cs
CulturesToGenerate=de
CulturesToGenerate=en
CulturesToGenerate=ja
CulturesToGenerate=ko
CulturesToGenerate=pl
CulturesToGenerate=ru
CulturesToGenerate=zh-Hans
CulturesToGenerate=es-ES
CulturesToGenerate=fr
CulturesToGenerate=hu
CulturesToGenerate=pt-BR
CulturesToGenerate=uk
CulturesToGenerate=tr
CulturesToGenerate=zh-Hant
ManifestName=Lead.manifest
ArchiveName=Lead.archive
PortableObjectName=Lead.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Crowdin

